### PR TITLE
Update dashboard data source connections to postgresql

### PR DESCRIPTION
**Pull request by xj2193**
- Change the data source connection to postgres tables
 - Clean up dashboards and remove unused tabs and data sources
 - Strip the sensitive information i.e. username in connections

TODO:
- Update the .cipher file with new postgres schema name

### CODE REVIEW

**Review by jp3477 — CHANGES_REQUESTED** [review]
Amazing work @xj2193! I just noticed two things that may need adjusting.

1. The NIH Grant Award Metrics - Custom View sheet is missing numbers in my view.
2. The DC Rates sheet in NIH Grant Award Metrics has a blue/red/orange colorscheme that is not present in the live dashboard.

If they are not showing like that for you, you can disregard.

**Comment by na2960** [comment]
I can make those changes^ and add to this pull request while you are out Zoey

**Comment by jp3477** [comment]
@na2960 I can do these changes, can you double check when they're done.

**Comment by xj2193** [comment]
@jp3477 do you still need the approval for the changes?

**Comment by na2960** [comment]
Welcome back @xj2193... I was going to check one more thing

**Comment by xj2193** [comment]
Sure thing

**Comment by na2960** [comment]
Good to go on my end!

**Review by jp3477 — APPROVED** [review]
Approved from me as well

**Comment by xj2193** [comment]
Thanks! I will merge the PR.

**Pull request merged**
