### PR TITLE
Fix dependency alerts

### PR DESCRIPTION
**Pull request by xj2193**
Updated requirements.txt to resolve the dependency alerts.

### CODE REVIEW

**Review by nishanthpp93 — COMMENTED** [review]
Thanks Zoey! I think there is another requirements file in zendesk_automation which needs the same updates (also verify if other updates are needed)

**Comment by xj2193** [comment]
Thanks @nishanthpp93 for your reminder. I will defer @em3697 to update the zendesk_automation folder so she will also know how to do it. @em3697 you can find the instructions I posted in slack channel.

**Comment by xj2193** [comment]
@nishanthpp93 if everything looks fine, I will merge this PR.

**Review by nishanthpp93 — APPROVED** [review]
Looks good, thanks Zoey and Elise! It would also be helpful to merge these requirements at some point in the future.

**Pull request merged**
