### PR TITLE
EHR-868

### PR DESCRIPTION
**Pull request by na2960**
Identified the use of participant_consent in 3 views that was changed to participant_module

### CODE REVIEW

**Review by jp3477 — APPROVED** [review]
Looks good! Thanks for doing this

**Comment by jp3477** [comment]
@na2960 You can go ahead and merge this in.

**Comment by xj2193** [comment]
@jp3477  the conflict has been resolved.

**Comment by jp3477** [comment]
> @jp3477 the conflict has been resolved.

Thanks @xj2193 !

**Pull request merged**
